/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XleAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface XleAmbulanceWlEditor {
        "ambulanceId": string;
        "apiBase": string;
        "entryId": string;
    }
    interface XleAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
}
export interface XleAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXleAmbulanceWlEditorElement;
}
export interface XleAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXleAmbulanceWlListElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLXleAmbulanceWlAppElement extends Components.XleAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLXleAmbulanceWlAppElement: {
        prototype: HTMLXleAmbulanceWlAppElement;
        new (): HTMLXleAmbulanceWlAppElement;
    };
    interface HTMLXleAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLXleAmbulanceWlEditorElement extends Components.XleAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXleAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLXleAmbulanceWlEditorElement, ev: XleAmbulanceWlEditorCustomEvent<HTMLXleAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXleAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLXleAmbulanceWlEditorElement, ev: XleAmbulanceWlEditorCustomEvent<HTMLXleAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXleAmbulanceWlEditorElement: {
        prototype: HTMLXleAmbulanceWlEditorElement;
        new (): HTMLXleAmbulanceWlEditorElement;
    };
    interface HTMLXleAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLXleAmbulanceWlListElement extends Components.XleAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXleAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLXleAmbulanceWlListElement, ev: XleAmbulanceWlListCustomEvent<HTMLXleAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXleAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLXleAmbulanceWlListElement, ev: XleAmbulanceWlListCustomEvent<HTMLXleAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXleAmbulanceWlListElement: {
        prototype: HTMLXleAmbulanceWlListElement;
        new (): HTMLXleAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "xle-ambulance-wl-app": HTMLXleAmbulanceWlAppElement;
        "xle-ambulance-wl-editor": HTMLXleAmbulanceWlEditorElement;
        "xle-ambulance-wl-list": HTMLXleAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XleAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface XleAmbulanceWlEditor {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: XleAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface XleAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: XleAmbulanceWlListCustomEvent<string>) => void;
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface XleAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface XleAmbulanceWlEditorAttributes {
        "entryId": string;
        "ambulanceId": string;
        "apiBase": string;
    }
    interface XleAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "xle-ambulance-wl-app": Omit<XleAmbulanceWlApp, keyof XleAmbulanceWlAppAttributes> & { [K in keyof XleAmbulanceWlApp & keyof XleAmbulanceWlAppAttributes]?: XleAmbulanceWlApp[K] } & { [K in keyof XleAmbulanceWlApp & keyof XleAmbulanceWlAppAttributes as `attr:${K}`]?: XleAmbulanceWlAppAttributes[K] } & { [K in keyof XleAmbulanceWlApp & keyof XleAmbulanceWlAppAttributes as `prop:${K}`]?: XleAmbulanceWlApp[K] };
        "xle-ambulance-wl-editor": Omit<XleAmbulanceWlEditor, keyof XleAmbulanceWlEditorAttributes> & { [K in keyof XleAmbulanceWlEditor & keyof XleAmbulanceWlEditorAttributes]?: XleAmbulanceWlEditor[K] } & { [K in keyof XleAmbulanceWlEditor & keyof XleAmbulanceWlEditorAttributes as `attr:${K}`]?: XleAmbulanceWlEditorAttributes[K] } & { [K in keyof XleAmbulanceWlEditor & keyof XleAmbulanceWlEditorAttributes as `prop:${K}`]?: XleAmbulanceWlEditor[K] };
        "xle-ambulance-wl-list": Omit<XleAmbulanceWlList, keyof XleAmbulanceWlListAttributes> & { [K in keyof XleAmbulanceWlList & keyof XleAmbulanceWlListAttributes]?: XleAmbulanceWlList[K] } & { [K in keyof XleAmbulanceWlList & keyof XleAmbulanceWlListAttributes as `attr:${K}`]?: XleAmbulanceWlListAttributes[K] } & { [K in keyof XleAmbulanceWlList & keyof XleAmbulanceWlListAttributes as `prop:${K}`]?: XleAmbulanceWlList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "xle-ambulance-wl-app": LocalJSX.IntrinsicElements["xle-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLXleAmbulanceWlAppElement>;
            "xle-ambulance-wl-editor": LocalJSX.IntrinsicElements["xle-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLXleAmbulanceWlEditorElement>;
            "xle-ambulance-wl-list": LocalJSX.IntrinsicElements["xle-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLXleAmbulanceWlListElement>;
        }
    }
}
